# Generated by Django 3.1.7 on 2022-01-14 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_auto_20220114_1607'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imovel',
            new_name='Imovei',
        ),
    ]
